# Generated by Django 5.0.6 on 2024-09-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xpos', models.FloatField()),
                ('Ypos', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('ClusterID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='algorithm.cluster')),
                ('ResourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.resource')),
            ],
            options={
                'unique_together': {('Xpos', 'Ypos', 'ResourceID')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RouteID', models.IntegerField()),
                ('StepNumber', models.IntegerField()),
                ('isDelivery', models.BooleanField()),
                ('Quantity', models.IntegerField()),
                ('EndNode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_node', to='algorithm.node')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='algorithm.resource')),
                ('StartNode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_node', to='algorithm.node')),
            ],
        ),
    ]
